### ISSUE TITLE
problem opening ports  with nftables 1.0.4-2

### ISSUE THREAD

**Issue by bolangi** [meetkool/NFT-firewall#1]
Thanks for publishing this script. After modifying it for my interface name, I found I was getting connection refused when ssh'ing from my router. I changed the tcp dport line as follows get it working.

       \-      tcp dport ssh   ct state new,untracked meter flood-ipv4-ssh  { ip saddr timeout 10s limit rate over 10/second }  add @blacklist-v4 { ip saddr timeout 1m }
        +      tcp dport { ssh, http, https } ct state new accept

I am running nft on devuan daedalus (debian bookworm).

Do you have any suggestions for getting the rate-limiting functionality to work?

**Comment by meetkool** [comment]
thank for updating me for now i am not actually using this srcipt at the movement so cannot help sorry ?
